sudo: required
dist: trusty
env:
  global:
  - secure: B6rGomaLIywtigHyn8jeMRaS8iS1dfrhzuDZujcn6dZ/KYDQv4+S4Wxbca5dom97NwmwgmOYwtV/wWPF/mpeWrhJgqt6m1DRbVGRxlB0Ho+gCDqZrWnR9NAyAsvz0lklTYGRQUqzhoGWVx11W4UWaNLiLQvsZClX7R9rfx5wkWZo2sX/3LW3l3x+z+Q1m/q2JtMkEdIthOXIyofErOQ4j26RGX2Z9CFeCnFrWex+UgFwf4W7NJtdjwZuAlFI7yD/Gz08/w8OUzwroxoyXSp5YJwhUYAFhwih/wawHL4woG6TrUrJtTj+q8hUhbk0k1lPcAkiJRtz4IeC8ox2+dbd/L6tOSjWDVhsgSJreAkPCyzEMJfxQxsPDJ6zNmfJdIEkgKuP2C+mQA8c3Dw9AUbtikgaauit4Fn2lDpvaSEjMxwNmiEpr5bQftnj9LDgwoyv7CyyrzJAMnsRbNab6wJB+kvI9i6ScQ7CDqRhsGXqGZ98kpkFdr3UraqdGpLWLd0OAMlggZeTrFjiv7hpLGPEGz5cz67vA4eyKBGR9xtvMJF0Pl5BlYz0QAFESSBH/RTU5/u1FCy2IQUORsxxjeOy1SEdwuACmGs6OF3l4hyBfTKbd+Vc2++SkiwLc1B8M2Ud2sJSOO9n322wY9+s3ZXpBYtpsCgoBbGMpkUqzbmxWBo=
  - secure: BHGdDuFw1NZHlq3k3n/o5Rd4lEsUOc4S4CfyxS72lY42eSS68hG6hFivUDu1h61GDewyWYncO1nz+rXEmB6VIZCXRm7RPFtJ2tkUwyXHbbYBNLG0EUyIHVwawO0hMnpcoR0pV+vboovbQdChgBh7xt4nISUCs9H/i2sU0luz+kZW05KWrqBOPBQrPgzvZ/IAdmVzsoSm9FV/qZmIzw95Irx0hnDavxLWPB2Qd7NfB2070qs6DNdICFfC3FGnYzziv2un7nSJIgAGn/+7WPLCTzEIyM9YBITE3e5qVHWuanpPXJs4G0Qn2xvD1f5KtdjKyKzLLdjQF0zR3OzcuXcUGZqSSVgErhXnJGffa2PyC6mqgllqXtPxe3kpISyngLzrBY7SulvceL+YUshuDMZshZpwS0e7FWJMSAr9JBwKAA73fO35fYkPljSUl3gNd1TkLordwlvjJnbJ8A9QVRZVBPtiRvWc/ATgkemMCT7hC+oRrKkSgqfbVfK6KL/hWxmjp43W2QvmuP3woAA/shT4XuiYFcCjByFuegy7R8fArxnqw3Tq35N2X+bx+av7W0BpsULCqXw0L/0pvl7rUn6XxFOkJM1BIdcKdtDKkQrR6pijH9O7OEU/WwoE7OAD2Fs8geMv+j7f7wCNtKfJFQWRDbxbfyfLN7RToPt3P8OQnPI=
  - secure: l0ngI1Cfq3gu5NbGi0vCPgO1kUReJs8gD2P4HNibm7UO9x2/cO9wHc0Ah05IZ2ZYpEwRejzSNAfKOJNe68+Hz0iRKEdqSpHbHViFzgbG0mMoUrdIijbQbhnUJlPz186sciWM2kuTUWMU9ql7hH5fZjGWd8yQH7PuktTnf7pgjnFNYf0cGok5m3UEwb+L0C+CcqU/m3Dqg5u5HCtrt64s9OTZnwxcAMOzfF6Xg+RXEhvZ9i7knUzXWkIo/G81TwD5M6jEe57OuUeVFanF42U9kRWCGf/8mBuuwCoSCFKOjGo1hubYRwt4CkNcMUSbgaT0jWEllWYNcirIgEr0Hq/jjmtlVnayB/42Rrb+mWBQz2gfQ9zJ1KI1EXRUdRMNCVhh0KGvgQhrm4AxVmRTCs1/ecXRrfmQo8IOiVL/5+JKEr0zI5kWDvlfNoxkcQ52rJAGZK4s+Md5GF2rKcrdXMfUeReZCYNnPUMm/jhMHYwp9Zga+gD3Qwq3TvCI1VOPhjOvbjdBh+aamohKWZ0MSek0I/Clj+EHRAoOG6GmP0Z6WD8dMWIT0MiRa+7gI5AO8JY5gXdy2uA1DFCONDyRq3hGQQBUOhMTzGmdArStNcs3Gsb21zUytfcVSHYk2/UE0/oy6lu6ro6N44hZK5VVZInc+rFETiQt0EtM1ogr+T1THDY=
  - secure: GQQ0wCWAiCAmxpz2uOV0Ccw7YYzxJlPzGtRLXuweT+b5mihxE0+5oRUvrcAUcqgqnr1+H4tr+a7B5QqPD0SL4aQEm6FFqoZjZNQd+tcyuzxfx/j/deB6GfkLBs5imCepyHw6pSl5fmyo61MGm6UYUcje0MSmxlVT2ilmAlVbJFotM6Ff8GvvUsr6nDhACpt+9Om0sXU75zgBQXNjEWdYTWqTvXhLI55dS9hmyFS7g22+FxppbWv23mlu7Lkod8kYOCbPbVYkAY8hupKDgx4Jvzd7h8lbXgmGL6Xk1tEDcp2NeThDU25NtILQXdob3t2wzXMFubhlMPcpvtMTrjFcaB6mgvfUtQJHFQLSnLMlg6SmfxuUtHfZ9Jo/1oQYMuxWd3jw3LDMyZxBlNS5o0IYvCZBJjJ433Jnn9qKwrjX9nAU8KlkBMHDEVP0/KVCcyVgCU6iooDzhaP1XEpnBVU1PS4ZY1nQRclbs6ZfCn/IqS4i/N0afXINPQ9G/Tn4D8zONkl5FDlcaLHJdB+JdKbjzXFVQFOdGuNcyFobdevnJkIM1pjECa2NJDQ6zywVhZlgZXBZ4b7XTx/vHMRcgP7g1xxhOyUC5eJVBpdPAttgO681ZW9ZLq3UaEQ7Ch+yFwExeOfvvtD975DNIQkmJf+CPJRf6s6r9DYJohixEv2U7PA=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins dependency:resolve -B
script:
- mvn clean install -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
